### ISSUE TITLE
example_blank_directory is missing 

### ISSUE THREAD

**Issue by aaprasad** [jenellefeather/model_metamers_pytorch#1]
Hi Jenelle! I wanted to generate metamers for my model and it seems pretty straight forward however in the `readme` it says to check out [model_analysis_folders/visual_networks/example_blank_directory](https://github.com/jenellefeather/model_metamers_pytorch/blob/master/model_analysis_folders/visual_models/example_blank_directory) or [model_analysis_folders/audio_networks/example_blank_directory](https://github.com/jenellefeather/model_metamers_pytorch/blob/master/model_analysis_folders/audio_models/example_blank_directory) but when I click the link it says "The `jenellefeather/model_metamers_pytorch` repository doesn't contain the `model_analysis_folders/visual_models/example_blank_directory` path in `master`." and the same for the auditory example. I also don't see it in the directories so I was wondering if you could add it. Thanks!
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/78439225/187044249-32e1f316-33e1-4bdb-8b8f-a9c614679069.png">

**Comment by jenellefeather** [comment]
Thanks for catching this! The link is updated and there are two example build_network files, one at each of the following paths:

https://github.com/jenellefeather/model_metamers_pytorch/tree/master/model_analysis_folders/visual_networks/example_blank_directory

https://github.com/jenellefeather/model_metamers_pytorch/tree/master/model_analysis_folders/audio_networks/example_blank_directory
