### ISSUE TITLE
Problem with CLIP_ViT-B_32

### ISSUE THREAD

**Issue by GreedyGroot** [jenellefeather/model_metamers_pytorch#12]
When using your code to generate the 16 class metamers of the 400 val images I got an error message saying: `model_metamers_pytorch/model_analysis_folders/visual_networks/CLIP_ViT-B_32/build_network.py", line 78, in forward
    logits = 100. * image_features @ self.zeroshot_weights
RuntimeError: expected scalar type Half but found Float`
The reason seems to be that matrix multiplication is used on 2 matrixes one of which is of dtype float32 and one is of dtype float16.
Changing the dtype of one of them like `image_features = image_features.to(torch.float32)` solved the problem.

**Comment by jenellefeather** [comment]
Thanks! I'm guessing this is a Pytorch version difference. I'll update the code to make those types explicit.

**Comment by jenellefeather** [comment]
Would you be able to check if the change made here solves your issue? 

https://github.com/jenellefeather/model_metamers_pytorch/pull/13

**Comment by GreedyGroot** [comment]
That change resolves the issue. Looking up this error message it seems like this issue appears only when using certain GPUs.

**Comment by jenellefeather** [comment]
Perfect. I'll merge it in (kind of a hack here to first build on the CPU, but that enforces it to be float32 in the easiest way with this code...)
